### ISSUE TITLE
Not found on package manager

### ISSUE THREAD

**Issue by cmditch** [savrcom/babel-plugin-safari-for-in-workaround#1]
```
➜  frontend git:(fix-safari-bug) yarn add babel-plugin-safari-for-in-workaround --dev
yarn add v1.22.11
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-plugin-safari-for-in-workaround: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/cmditch/projects/real-kinetic/witful/packages/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  frontend git:(fix-safari-bug) 
```

**Comment by teppix** [comment]
Thanks for the report!

We don't intend to release this package as the transform is a bit dangerous, and it's not meant to be used long term.

You can install the package directly from git using the following in your `package.json`

```
"babel-plugin-safari-for-in-workaround": "https://github.com/savrcom/babel-plugin-safari-for-in-workaround",
```

I would however recommend that you fork the repository if you want to use it in production, for better reliability if there are changes to this repository in the future.

You are of course also free to publish the package yourself if you want to.

**Comment by teppix** [comment]
The instructions are obviously wrong. Reopening until fixed.
